
---------------------------------------------------------------
/*
-- 	Name		: adBatchSetGamma22
--	Date		: 2015/02/25
--	Url			: www.ashishdani.com
-- 	Tested		: 3Ds Max 2014

-- This script is used to Enable the Gamma correction of the file &
-- Set the File Input and Output gamma to 2.2
-- This is a Batch Script version
*/
---------------------------------------------------------------


IDisplayGamma.colorCorrectionMode = #gamma
displayGamma = 2.2
FileInGamma = 2.2
FileOutGamma = 2.2